# Generated by Django 5.2.9 on 2026-01-04 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название жанра')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='RecordCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('M', 'Mint (идеальное)'), ('G', 'Good (хорошее)'), ('F', 'Fair (удовлетворительное)'), ('P', 'Poor (плохое)')], max_length=4, verbose_name='Состояние')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Состояние пластинки',
                'verbose_name_plural': 'Состояния пластинок',
                'ordering': ['grade'],
            },
        ),
        migrations.CreateModel(
            name='VinylRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название альбома')),
                ('artist', models.CharField(max_length=200, verbose_name='Исполнитель')),
                ('year', models.IntegerField(verbose_name='Год выпуска')),
                ('estimated_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Оценочная стоимость')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена покупки')),
                ('format', models.CharField(choices=[('LP', 'LP (альбом)'), ('EP', 'EP (мини-альбом)'), ('S', 'Сингл'), ('BOX', 'Бокс-сет')], default='LP', max_length=4, verbose_name='Формат')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('condition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vinyl.recordcondition', verbose_name='Состояние')),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vinyl.genre', verbose_name='Жанр')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Виниловая пластинка',
                'verbose_name_plural': 'Виниловые пластинки',
                'ordering': ['artist', 'year'],
            },
        ),
    ]
